import React from 'react';
import { NavLink } from 'react-router-dom';

const menuItems = [
  {
    icon: '📊',
    label: 'Overview',
    description: 'System status and metrics.',
    to: '/',
  },
  {
    icon: '🤖',
    label: 'Generate Agents',
    description: 'Create new agents from transcripts and briefs.',
    to: '/generate',
  },
  {
    icon: '🗂️',
    label: 'Agent Library',
    description: 'Browse and manage existing AI agents.',
    to: '/agents',
  },
  {
    icon: '🧠',
    label: 'Detailed Personas',
    description: 'Rich persona insights generated by the AI.',
    to: '/personas',
  },
  {
    icon: '💬',
    label: 'Group Chat',
    description: 'Facilitate multi-agent collaboration.',
    to: '/group-chat',
  },
  {
    icon: '📦',
    label: 'Chat Archive',
    description: 'Review past conversations with summaries.',
    to: '/archive',
  },
  {
    icon: '🎨',
    label: 'Design Feedback',
    description: 'Collect UI & UX feedback from agents.',
    to: '/design-feedback',
  },
  {
    icon: '📄',
    label: 'PRD Viewer',
    description: 'Clean, scannable PRD reading view.',
    to: '/prd/demo',
  },
];

const Sidebar = () => (
  <aside className="fixed left-0 top-16 h-full w-64 overflow-y-auto border-r border-gray-200 bg-white">
    <nav className="space-y-1 p-4">
      {menuItems.map((item) => (
        <NavLink
          key={item.to}
          to={item.to}
          className={({ isActive }) =>
            [
              'flex w-full items-start gap-3 rounded-xl px-4 py-3 text-left transition-colors',
              isActive
                ? 'bg-blue-50 text-blue-700 ring-1 ring-blue-200'
                : 'text-gray-700 hover:bg-gray-50',
            ].join(' ')
          }
        >
          <span className="text-lg leading-none">{item.icon}</span>
          <span className="flex-1 min-w-0">
            <span className="block text-sm font-semibold">{item.label}</span>
            <span className="mt-1 block text-xs text-gray-500">{item.description}</span>
          </span>
        </NavLink>
      ))}
    </nav>
  </aside>
);

export default Sidebar;
